export const estadoInicialComun = {
    propietario: '',
    propietarioTipo: '',
    tipo: '',
    id: null,
    inmobiliaria: null,
    broker: null,
    enVenta: false,
    enAlquiler: false,
    titulo: null,
    descripcion: null,
    destacada: false,
    url: null,
    Ubicacion: {
        departamento: null,
        ciudad: null,
        barrio: null,
        distanciamarmetros: null,
        frentealmar: null,
        direccion: null,
        lat: null,
        lon: null
    },
    venta: {
        precio: null,
        mda: null,
        fechavigencia: null,
        permuta: null,
        oferta: null,
        financia: null,
        renta: null,
        porcentajerenta: null,
        saldobanco: null
    },
    alquiler: {
        VigenciaAlquiler: null,
        PrecioPubliacionAlquiler: null,
        Enero: null,
        EneroQuincena1: null,
        EneroQuincena2: null,
        Febrero: null,
        FebreroQuincena1: null,
        FebreroQuincena2: null,
        Reveion: null,
        Carnaval: null,
        SemanaSanta: null,
        AnualPesos: null,
        InvernalPesos: null,
        AnualDolares: null,
        PeriodoPrecioAlqAnual: null,
        AnualTestigo: null,
        CotizacionDolar: null,
        InvernalDolares: null,
        Diciembre: null,
        DiciembreQuincena1: null,
        DiciembreQuincena2: null,
        Marzo: null,
        MarzoQuincena1: null,
        MarzoQuincena2: null,
        Temporada: null,
        AceptaMascota: false,
        AceptaFumador: false,
        AceptaNinos: false,
        GDeposito: false,
        GPropiedad: false,
        GAnda: false,
        GPorto: false,
        GCGN: false,
        GMVOTMA: false,
        GSura: false,
        GLUC: false,
        GCIncluidos: false
    },
    fotos: [{ url: null, descripcion: null }]
};

// Extender para Casa
export const estadoInicialCasa = {
    ...estadoInicialComun,
    tipo: 'Casa',
    Caracteristicas: {
        vista: null,
            tipocasa: null,
            orientacion: null,
            disposicion: null,
            frentealmar: null,
            distanciamarmetros: null,
            superficieterreno: null,
            superficieedificado: null,
            superficiecubierta: null,
            superficiesemicubierta: null,
            frente: null,
            fondo: null,
            tenencia: null,
            totaldormitorios: null,
            banos: null,
            suites: null,
            toilettes: null,
            cocina: null,
            living: null,
            comedor: null,
            livingcomedor: null,
            comedordiario: null,
            capacidadpersonas: null,
            cantidadcamas: null,
            dependenciaservicio: null,
            equipamiento: null,
            caracteristicas: null,
            comodidades: null,
            banoservicio: null,
            playroom: null,
            propiedadhorizonal: null,
            estufalena: null,
            cochera: null,
            calefaccion: null,
            garage: null,
            estacionamiento: null,
            estado: null,
            cantidadplantas: null,
            paredes: null,
            pisos: null,
            techo: null,
            saneamiento: null,
            piscina: null,
            parrillero: null,
            fechaconstruccion: null,
            muebles: null,
            amoblado: null,
            amovred: null,
            lavadero: null,
            monedacontribucion: null,
            contribucioninmobiliaria: null,
            frecuenciacontribucion: null,
            monedaprimaria: null,
            impuestoprimaria: null,
            frecuenciaprimaria: null,
            gastoscomunes: null,
            monedagastos: null,
            frecuenciagastos: null,
            alarma: null,
            youtube: null,
            matterport: null
    }
};

// Extender para Apartamento
export const estadoInicialApartamento = {
    ...estadoInicialComun,
    tipo: 'Apartamento',
    Caracteristicas: {
        parrillero: null,
            playroom: null,
            mucamas: null,
            servicioplaya: null,
            tipoedificio: null,
            asensores: null,
            piscina: null,
            estacionamientovisitas: null,
            sauna: null,
            gimnasio: null,
            canchas: null,
            vigilancia: null,
            numeropiso: null,
            aptosxpiso: null,
            cantidadpisos: null,
            totaldormitorios: null,
            mediodormitorio: null,
            banos: null,
            suites: null,
            toilettes: null,
            cocina: null,
            living: null,
            comedor: null,
            livingcomedor: null,
            capacidadpersonas: null,
            cantidadcamas: null,
            caracteristicas: null,
            equipamiento: null,
            comodidades: null,
            amenities: null,
            monedacontribucion: null,
            contribucioninmobiliaria: null,
            frecuenciacontribucion: null,
            monedaprimaria: null,
            impuestoprimaria: null,
            frecuenciaprimaria: null,
            gastoscomunes: null,
            monedagastos: null,
            frecuenciagastos: null,
            antiguedad: null,
            dependenciaservicio: null,
            banoservicio: null,
            estufalena: null,
            cochera: null,
            garage: null,
            estacionamiento: null,
            estado: null,
            calefaccion: null,
            superficietotal: null,
            superficiepropia: null,
            superficiecubierta: null,
            superficiesemicubierta: null,
            superficiebalcon: null,
            baulera: null,
            lavadero: null,
            EsPH: null,
            muebles: null,
            amoblado: null,
            amovred: null,
            terrazabalcon: null,
            comedordiario: null,
            vista: null,
            tenencia: null,
            orientacion: null,
            disposicion: null,
            idedificio: null,
            fondoreserva: null,
            monedafondo: null,
            vigenciafondo: null,
            youtube: null,
            matterport: null
    }
};

// Extender para Terreno
export const estadoInicialTerreno = {
    ...estadoInicialComun,
    tipo: 'Terreno',
    Caracteristicas: {
        vista: null,
        distanciamarmetros: null,
        frentealmar: null,
        superficie: null,
        frente: null,
        fondo: null,
        lateral: null,
        esquina: null,
        arbolado: null,
        divisible: null,
        sobreruta: null,
        luz: null,
        agua: null,
        saneamiento: null,
        formaterreno: null,
        accesocampo: null,
        fot: null,
        subzona: null,
        aptoph: null,
        supeficieedificable: null,
        cantidadpisos: null,
        alambrado: null,
        alto: null,
        monedacontribucion: null,
        contribucioninmobiliaria: null,
        monedaprimaria: null,
        impuestoprimaria: null,
        tenencia: null,
        youtube: null,
        matterport: null
    }
};

// Extender para Local
export const estadoInicialLocal = {
    ...estadoInicialComun,
    tipo: 'Local',
    Caracteristicas: {
        fechamodificado: null,
        vista: null,
        distanciamarmetros: null,
        frentealmar: null,
        superficie: null,
        superficiecubierta: null,
        superficiesemicubierta: null,
        frente: null,
        fondo: null,
        metrosentrepiso: null,
        metrossubsuelo: null,
        banos: null,
        ubicacion: null,
        idealpara: null,
        tenencia: null,
        monedacontribucion: null,
        contribucioninmobiliaria: null,
        monedaprimaria: null,
        impuestoprimaria: null,
        gastoscomunes: null,
        monedagastos: null,
        frecuenciagastos: null,
        tipo: null,
        youtube: null,
        matterport: null
    }
};

export const estadoInicialChacra = {
    ...estadoInicialComun,
    tipo: 'Chacra',
    Caracteristicas: {
        vista: null,
        distanciamarmetros: null,
        frentealmar: null,
        superficieterreno: null,
        superficieterrenom2: null,
        superficieedificado: null,
        totaldormitorios: null,
        banos: null,
        suites: null,
        cocina: null,
        living: null,
        comedor: null,
        livingcomedor: null,
        zonas: null,
        forestacion: null,
        aguadas: null,
        instalaciones: null,
        galpones: null,
        casapersonal: null,
        cursoagua: null,
        tajamar: null,
        riego: null,
        invernaculos: null,
        alambrados: null,
        canada: null,
        arroyo: null,
        costario: null,
        pozoagua: null,
        monte: null,
        embarcadero: null,
        potreros: null,
        camaras: null,
        preciohectareas: null,
        enventa: null,
        enalquiler: null,
        tenencia: null,
        contribucioninmobiliaria: null,
        impuestoprimaria: null,
        youtube: null,
        matterport: null
    }
};